import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[window]
padding = { x = 5, y = 10 }
decorations = "Transparent"
opacity = 0.85
blur = false

[font]
normal = { family = "MonoLisa", style = "Light" }
size = 16

[colors]

[terminal]
osc52 = "CopyPaste"


