import = [
  "~/.config/alacritty/tokyo-night.toml"
]

[window]
padding = { x = 5, y = 5 }
decorations = "Buttonless"
opacity = 0.85
blur = false

[font]
normal = { family = "SauceCodePro Nerd Font", style = "Regular" }
size = 18

[colors]

[terminal]
osc52 = "CopyPaste"


